resource "local_file" "pet" {
  filename = var.filename
  content = "Myfavorite pet is ${random_pet.my-pet.id}"

  depends_on = [   # explicit dependency, local file create after random_pet
    random_pet.my-pet
  ]
}

resource "random_pet" "my-pet" {
  prefix = var.prefix
  separator = var.separator
  length = var.length
}
output pet-name {
  value = random_pet.my-pet.id
  description = "Record the value of pet ID generated by the random_pet resource"
}