apiVersion: apps/v1
kind: Deployment
metadata:
  name:  result-app-deployment
  labels:
    name: result-app-deployment
    app: demo-voiting-app
spec:
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: voting-app-pod
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80