apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector: # identify which node to use
    app: myapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
