apiVersion: v1
kind: Pod
metadata:
  name: "MYAPP"
  namespace: default
  labels:
    app: "MYAPP"
spec:
  containers:
    - name: MYAPP
      image: "debian-slim:latest"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: size
              operator: In
              values:
                - Large
                - Medium
            # - key: size
            #   operator: NotIn
            #   values:
            #    - Small

            # - key: size
            #   operator: Exists - when the label exists