apiVersion: v1
kind: Pod
metadata:
  name: "nginx"
  labels:
    app: "nginx"
    type: frontend
spec:
  containers:
    - name: nginx
      image: "nginx"
      command: # If the pod goes into the crashloopbackoff
        # then add the command sleep 1000
        - sleep
        - "3600"
