apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: paswrd
  # Example:
  # password: {{ .Values.password | b64enc }}
env:
  - name: ENV_VAR
    valueFrom:
      secretKeyRef:
        name: name
        key: key
