apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-name
  namespace: quota-ns
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi
    pods: "10"
    # persistentvolumeclaims: '5'
    # requests.storage: 5Gi
