apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXYwNEcxQ21jYk1LNkZTZDZCR2VZeGJvR1p3cWpvdnNFN1YyZVNVSklzK2dDClVoM0RheEZLc0YzZmJsajc1ZGlHSy9oZSs5VlVoVnFaVjkrZU92NFEyOGxJS2Zhek1qbktpTkZlREJZWStTaUsKMWlSaGZNMm1NbFExaXhKUE5BUGFwR04rNS93R09jT3o3RnJXOE1ycmpxU2R5UWUzaWFGbi9vZXVXUEZyUW1ZagpEMDlCU3FydjQraEFWNjgvdThVc2lyODV1SjRKNlhkYkdCcUhKS0kwdUh0YnROamlGemV6UWFySlhLZnI3TDlrCitjQzNieCtqMHpmOWZ3dWIwYXZGOXZHSTVoUC9JbjdOVWZIdHNPOGRWTnp6aEVGbkZsRXI1WFIrSFJ0Wis3S0YKbVdkbFJnWXJuTTFQb0FScENmTldpRXJ6TytKYkFXSGdLZjFvc3lXZWNRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSjJsL3dUSFNNbkRCdTE1TkZleWEwY3ZtWFhWRzdvbVJjZE5wZXo1OWMrZENaVk9aOWdtClJiZmgzalpybm14eDVpLzhxUHRUdXN1cGRHZnB3WVBPeDVmZFJEbzVGcGJOVUdOcGFZdUYvanFmaWw5dmNjWFcKeDhKd0dVVnpXOXU2MXp4WEczOUwrTENJSWJXY1JyMFBVbnNCL1RBNHNZUVNNaXJycnBGVktDMUZkS3BvOXVRMApRTjBwd2F1NEM1V3ozcGRZL1B0T25ObXVVbGt5WVRyVkhhRFg5ZEovekNWdE9Cc2JyUGg5OXF5b2ROVHhMbXZXCnJ4K3dVMkZ0V0pPWkhaNUdkS29XcDJhLy8yanlNazgwUzVjQ0FqMmVLa1RybnkzS0l6Ly9rTHRWa3QycGRnZDgKWUZyR2k0NlRUYVN1dkJHYkhNTGZTU2xwSmxuOFJYNThuWW89Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
